services:
  redis:
    image: redis:latest
    container_name: redis
    command: >
      redis-server --requirepass redis
    networks:
      - auth

  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: auth
    networks:
      - auth

  auth-server:
    container_name: auth-server
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mongodb
      - redis
    networks:
      - auth

  reverse-proxy:
    container_name: reverse-proxy
    build: ./nginx
    depends_on:
      - auth-server
    ports:
      - "443:443"
    networks:
      - auth
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  mongodb_data:

networks:
  auth:
    driver: bridge
