services:
  redis:
    image: redis:latest
    container_name: redis
    command: >
      redis-server --requirepass redis
    networks:
      - auth

  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - auth

  auth-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mongodb
      - redis
    ports:
      - "5000:5000"
    networks:
      - auth

volumes:
  mongodb:

networks:
  auth:
    driver: bridge
