services:
  redis:
    image: redis:latest
    container_name: redis-dev
    command: >
      redis-server --requirepass redis
    networks:
      - auth

  mongodb:
    image: mongo:latest
    container_name: mongo-dev
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: auth
    networks:
      - auth

  mongo-express:
    image: mongo-express
    container_name: mongo-express-dev
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/auth
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - auth

  auth-server:
    container_name: auth-server-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=development
    networks:
      - auth
    command: ["npm", "run", "dev"]

volumes:
  mongodb:

networks:
  auth:
    driver: bridge
