services:
  redis:
    image: redis:latest
    container_name: redis-dev
    command: >
      redis-server --requirepass redis
    networks:
      - auth

  mongodb:
    image: mongo:latest
    container_name: mongo-dev
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - auth

  auth-server:
    container_name: auth-server-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - redis
    networks:
      - auth

volumes:
  mongodb_data:

networks:
  auth:
    driver: bridge
